In [1]:
import numpy as np

In [4]:
a = np.array([1, 2, 3])
a

array([2, 3, 4])

In [8]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
matrix[:,2]

array([3, 6, 9])

In [13]:
matrix + 1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [14]:
matrix[matrix > 4]

array([5, 6, 7, 8, 9])

In [15]:
matrix % 2 == 0

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [16]:
matrix[matrix % 2 == 0]

array([2, 4, 6, 8])

In [17]:
step1 = matrix % 2
step2 = step1 == 0
step3 = matrix[step2]

step3

array([2, 4, 6, 8])